const ActionTypes = {
  FETCH_COURSES: 'FETCH_COURSES',
  FETCH_RANDOM_COURSES: 'FETCH_RANDOM_COURSES',
  FETCH_COURSE: 'FETCH_COURSE',
  UPDATE_COURSE: 'UPDATE_COURSE',
  CREATE_COURSE: 'CREATE_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',
  SEARCH: 'SEARCH',
  FETCH_PROFESSORS: 'FETCH_PROFESSORS',
  FETCH_PROFESSOR: 'FETCH_PROFESSOR',
  UPDATE_PROFESSOR: 'UPDATE_PROFESSOR',
  CREATE_PROFESSOR: 'CREATE_PROFESSOR',
  DELETE_PROFESSOR: 'DELETE_PROFESSOR',
};

export default ActionTypes;
